issueTrackerURL = "https://github.com/ascpixi/disconnect-packet-fix/issues"
license = "MIT"

[[mods]]
modId = "disconnect_packet_fix"
version = "${version}"
displayName = "Disconnect Packet Fix"
authors = "ascpixi"
description = '''
Works around the MC-271325 bug (unknown disconnect packet)
'''
logoFile = "META-INF/icon.png"

[[dependencies.disconnect_packet_fix]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.15-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.disconnect_packet_fix]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,27.0)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "disconnect-packet-fix.mixins.json"
